### ISSUE TITLE
Thema Perspective (W3C Themen) fixieren

### ISSUE THREAD

**Issue by cnoss** [th-koeln/mi-master-wtw#36]
Bitte pro Thema eine eigene Seite im [Repo-Wiki](https://github.com/th-koeln/mi-master-wtw/wiki) anlegen und folgende Fragen beantworten:

- Welches [Format](https://th-koeln.github.io/mi-master-wtw/formate/) wird erarbeitet?
- Was ist die grobe Struktur?
- Welche der Bewertungskritierien sollen Anwendung finden?

**Comment by slemke** [comment]
[Generic Sensor API (Lemke)](https://github.com/th-koeln/mi-master-wtw/wiki/Generic-Sensor-API-(Lemke))

**Comment by tolja** [comment]
[W3C Payment Request API (Walger)](https://github.com/th-koeln/mi-master-wtw/wiki/W3C-Payment-Request-API-(Walger))

**Comment by tolja** [comment]
[WebAssembly (Walger)](https://github.com/th-koeln/mi-master-wtw/wiki/WebAssembly-(Walger))
